name = "Link"
description = "A styled hyperlink component."

[[examples]]
name = "link"

[[examples]]
name = "link button"
title = "As Button"
description = "Use render_as to render a Link component with Button styling."

[[examples]]
name = "link badge"
title = "As Badge"
description = "Use render_as to render a Link component with Badge styling."


[[references]]
name = "Link"
description = "Creates a styled hyperlink."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#attributes">a</a> \
attributes."""
attrs = [
  { attr = "render_as", attr_type = "String", default = """""""", description = """Set whether or \
    not this Link should appear as something else. This is similar to asChild. Accepted values \
    are "button" | "badge". """ },
  { attr = "mimetype", attr_type = "String", default = """""""", description = """Renamed <a> \
    `type` attribute to avoid name collisions.""" },
  { attr = "size", attr_type = "String", default = """""""", description = """For use with \
    render_as, specify the size to render the element.""" },
  { attr = "variant", attr_type = "String", default = """"link"""", description = """For use with \
    render_as, specify the variant of the element to render.""" },
]
