name = "Dropdown Menu"
description = """Displays a menu to the user — such as a set of actions or functions — triggered \
by a button."""

[info]
title = "This component uses newly available browser features"
description = """"<p>"This component uses CSS Anchor Positioning which has only been widely \
supported since January 2026. If you're targeting older or less mainstream browsers then maybe \
this component isn't for you, yet. "</p><p>" Alternatively you can use Singlestage 0.4 which \
positions the component correctly but with limited flexibility for alignment, or roll your own \
using Singlestage CSS classes for consistent styling. "</p><singlestage::Link style="color: \
var(--foreground)" href="https://caniuse.com/css-anchor-positioning"> "More Info" \
</singlestage::Link>""""

[[examples]]
name = "Dropdown Menu"

[[references]]
name = "DropdownMenu"
description = "Contains all the parts of a dropdown menu."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "DropdownMenuContent"
description = "The component that pops out when the dropdown menu is open."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "DropdownMenuGroup"
description = "Contains multiple items."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "DropdownMenuItem"
description = "Contains a menu item."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/li#attributes">li</a> \
attributes."""
attrs = [
  { attr = "disabled", attr_type = "bool", default = "false", description = """Controls \
    whether the item appears disabled or not.""" },
  { attr = "variant", attr_type = "String", default = """""""", description = """Set the display \
    variant of the item.""" },
]

[[references]]
name = "DropdownMenuLabel"
description = "Labels groups."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "DropdownMenuSeparator"
description = "Visually separates groups of menu items."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "DropdownMenuShortcut"
description = "Displays next to the item content and indicates keyboard shortcuts."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "DropdownMenuTrigger"
description = "Provides context to a Button that triggers a DropdownMenu."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []
