name = "Button"
description = "Displays a button."

[[examples]]
name = "Button"

[[examples]]
name = "Button Size"
title = "Button Size"
description = "Use the size prop to change the size of the button."

[[examples]]
name = "Button default"
title = "Default"

[[examples]]
name = "Button outline"
title = "Outline"

[[examples]]
name = "Button secondary"
title = "Secondary"

[[examples]]
name = "Button ghost"
title = "Ghost"

[[examples]]
name = "Button destructive"
title = "Destructive"

[[examples]]
name = "Button link"
title = "Link"

[[examples]]
name = "Button Icon"
title = "Icon"

[[examples]]
name = "Button with icon"
title = "With Icon"

[[examples]]
name = "button rounded"
title = "Rounded"

[[examples]]
name = "button spinner"
title = "Spinner"

[[examples]]
name = "button button group"
title = "Button Group"

[[examples]]
name = "button link as button"
title = "Link"

[[references]]
name = "Button"
description = "Creates a button."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/button#attributes">button</a> \
attributes."""
attrs = [
  { attr = "as_child", attr_type = "bool", default = """false""", description = """This component will \
    render without styling.""" },
  { attr = "button_type", attr_type = "String", default = """"submit"""", description = """Renamed button \
    `type` attribute to avoid name collisions.""" },
  { attr = "dismiss", attr_type = "bool", default = """false""", description = """Toggle whether clicking \
    this button dismisses its parent popover.""" },
  { attr = "invalid", attr_type = "bool", default = "false", description = """Toggle whether or not \
    the input is disabled.""" },
  { attr = "size", attr_type = "String", default = """""""", description = """Specify the size to \
    render the button. Accepted values: "small" | "large" | "icon" | "sm-icon" | "lg-icon"""" },
  { attr = "variant", attr_type = "String", default = """"primary"""", description = """Specify \
    the style of button to render. Accepted values: "primary" | "secondary" | "outline" | "ghost" \
    | "link" | "destructive"""" },
]
