name = "Select"
description = "Displays a list of options for the user to pick from—triggered by a button."

[[examples]]
name = "select"

[[examples]]
name = "select placeholder"
title = "Placeholder"
description = "A placeholder can be set to hint to the user what type of value this field expects."

[[examples]]
name = "select default"
title = "Default"
description = "Set a default value to be pre-selected."

[[examples]]
name = "select groups"
title = "Groups"
description = "Use SelectOptGroup to organize options into categories."

[[examples]]
name = "select disabled"
title = "Disabled"
description = "Set the disabled prop on the Select component to disable the select."

[[examples]]
name = "select invalid"
title = "Invalid"
description = "Set the invalid prop on the Select component to toggle invalid styling."

[[examples]]
name = "select multiple"
title = "Multiple"
description = "Multiple select is supported."

[[references]]
name = "Select"
description = "Contains all the parts of the Select."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/select#attributes">select</a> \
attributes."""
attrs = [
  { attr = "default", attr_type = "String", default = """""""", description = """Set the default \
    selected value. Setting value overrides this setting.""" },
  { attr = "invalid", attr_type = "bool", default = "false", description = """Toggle invalid \
    appearance and behavior.""" },
  { attr = "placeholder", attr_type = "String", default = """""""", description = """Sets a \
    placeholder value displayed on initial load. Setting default will override this value.""" },
  { attr = "value", attr_type = "String", default = """""""", description = """A reactive value \
    coupled to the currently selected item's value.""" },
]

[[references]]
name = "SelectOptGroup"
description = "Contains a group of items for the Select."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/optgroup#attributes">optgroup</a> \
attributes."""
attrs = []

[[references]]
name = "SelectOption"
description = "Contains an item with a value to be selected."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/option#attributes">option</a> \
attributes."""
attrs = []
