name = "Checkbox"
description = "A control that allows the user to toggle between checked and not checked."

[[examples]]
name = "checkbox"

[[examples]]
name = "checkbox invalid"
title = "Invalid State"
description = "Set invalid on either the Checkbox or a Field wrapper to display an invalid state."

[[examples]]
name = "checkbox basic"
title = "Basic"
description = "Pair the checkbox with Field and FieldLabel for proper layout and labeling."

[[examples]]
name = "checkbox description"
title = "Description"
description = "Use FieldContent and FieldDescription for helper text."

[[examples]]
name = "checkbox disabled"
title = "Disabled"
description = "Use the disabled prop to prevent interaction."

[[examples]]
name = "checkbox group"
title = "Group"
description = "Use multiple fields to create a checkbox list."

[[examples]]
name = "checkbox table"
title = "Table"

[[examples]]
name = "subtext"

[[examples]]
name = "form"

[[examples]]
name = "group"
title = "Checkbox Group"

[[references]]
name = "Checkbox"
description = "A control that allows the user to toggle between checked and not checked."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a>, \
<a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input#attributes">input</a>, \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/checkbox#additional_attributes">checkbox</a> \
attributes."""
attrs = [
  { attr = "checked", attr_type = "Reactive<bool>", default = "false", description = """A \
    reactive signal coupled to the checkbox's checked value.""" },
]

[[references]]
name = "CheckboxGroup"
description = "Contains all the parts of a checkbox group."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/fieldset#attributes">fieldset</a> \
attributes."""
attrs = [
  { attr = "invalid", attr_type = "Reactive<bool>", default = "false", description = """A \
    reactive signal that toggles whether all the children Checkboxes appear invalid or not.""" },
  { attr = "value", attr_type = "Reactive<Vec<String>>", default = "[]", description = """A \
    dynamic list of all the values of checked children Checkboxes.""" },
]
